### ISSUE TITLE
It won't build

### ISSUE THREAD

**Issue by avacariu** [fosskers/tetris#1]
I was all like "OOOH TETRIS! :smile:"

But Make was all like `*** No rule to make target 'cog/shaders/shaders.o', needed by 'fetris'.  Stop.` :angry: 

Is this going to be fully functional at some point, or is it just a backup for your assignment?

**Comment by fosskers** [comment]
No I'd like it to be fully functional. I've made this seperate repo because the Assignment takes it in too much of a non-Tetris direction.

All you need to do to get this working is: `git clone https://github.com/fosskers/cog.git` in the tetris repo. `cog` is my OpenGL helper lib for C.

**Comment by fosskers** [comment]
It still needs Music, levels, proper block colouring, the Fruit logic ripped out, time, etc.

**Comment by fosskers** [comment]
Builds now?

**Comment by avacariu** [comment]
It does, but it also segfaults.

I'll send you a pull request with Ubuntu build instructions in the README.
